server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            searchLocations: file:///Users/elias_rojas/eclipse-workspace/configserver/src/main/resources/config/licensingservice