server:
  port: 8888
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            searchLocations: file:///D:/Java projects/Git repositories\microservices\configserver\src\main\resources\config\licensingservice
#           macOS: Users/elias_rojas/eclipse-workspace/configserver/src/main/resources/config/licensingservice
#           workPC: D:\Java projects\Git repositories\microservices\configserver\src\main\resources\config\licensingservice