server:
  port: 8889
spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
            searchLocations: file:///D:\Java projects\Git repositories\microservices\configserver\src\main\resources\config\licensingservice
#           macOS: Users/elias_rojas/develop/microservices/configserver/src/main/resources/config/licensingservice
#           workPC: D:\Java projects\Git repositories\microservices\configserver\src\main\resources\config\licensingservice